"""
GuideLLM Real-World Throughput & Latency Benchmark

Sends concurrent users through a real or synthetic dataset via GuideLLM's
Poisson-arrival scheduler and returns raw performance metrics.

Score and pass/fail are NOT computed here — the platform evaluator uses
per-benchmark MetricConfig rules (stored in BenchmarkModule.metric_configs_json).

Default evaluation (default_metric_configs):
  Score: 0.5 × (input_tps / baseline) + 0.5 × (output_tps / baseline)  [ratio, uncapped]
  Redlines: TTFT/TPOT/ITL P99 & P50 max thresholds, uptime min threshold
            (P90 is reported too, but display-only)

Load is generated by guidellm: Poisson arrivals, with an optional ShareGPT
dataset file; without one it sends random tokens of the requested shape.
"""
from __future__ import annotations

import os
import sys
import re
import threading
import time
from typing import Optional

from pydantic import BaseModel, Field

from bench.modules.base import (
    AllRequestsFailed, BenchmarkTimeout, EndpointConfig, MetricConfig, MetricDescriptor,
    ModuleResult, ProgressCallback, TestModule, _noop_progress,
)
from utils.logger import logger


class PerfGuidellmParams(BaseModel):
    backend: str = Field(
        default="guidellm",
        description="Load backend. Only 'guidellm' is supported.",
    )
    concurrency: int = Field(default=5, ge=1, le=4096, description="Concurrent users / concurrency level")
    input_tokens: int = Field(default=50000, ge=1, le=1_000_000_000, description="Input tokens per request")
    output_tokens: int = Field(default=1500, ge=1, description="Max output tokens per request")
    max_seconds: float = Field(default=300.0, ge=1.0, le=604800.0, description="Test duration in seconds")
    request_timeout: float = Field(default=120.0, ge=1.0, le=86400.0, description="Per-request timeout in seconds")
    warmup_seconds: float = Field(default=30.0, ge=0.0, le=86400.0, description="[guidellm] Warmup duration in seconds")
    dataset_path: Optional[str] = Field(
        default=None,
        description="[guidellm] Path to ShareGPT-format dataset file. Leave blank to use random tokens."
    )
    processor_path: Optional[str] = Field(
        default=None,
        description=(
            "[guidellm] Tokenizer/processor directory for accurate token counts. "
            "Relative paths resolve against the project root (e.g. "
            "'/models/Qwen3-8B' or a HF repo id). Leave blank to use the built-in "
            "default or the PROCESSOR_PATH env var."
        ),
    )


# Card baseline for the display-only card-normalized TPM metrics
# (`*_tpm_card_norm`, computed by the platform worker): throughput is rescaled
# as if the endpoint ran on this many cards.
CARD_NORM_BASELINE = 8


class _GuidellmBudgetMixin:
    """Declares the guidellm deadline as this module's own wall-clock bound.

    Without this the worker's backstop would be sized off `params.max_seconds`,
    which for guidellm is the duration of ONE concurrency level and excludes
    warmup and the in-flight drain — so the backstop could land *below* the
    deadline guidellm itself enforces and abort healthy runs. Reuses the exact
    function the run path uses, so the two can never drift.
    """

    @classmethod
    def _budget_rates(cls, params) -> list:
        raise NotImplementedError

    @classmethod
    def time_budget_seconds(cls, params) -> "float | None":
        try:
            return compute_guidellm_run_timeout(
                cls._budget_rates(params),
                getattr(params, "warmup_seconds", 0.0),
                getattr(params, "max_seconds", 0.0),
                getattr(params, "request_timeout", 0.0),
            )
        except Exception:
            return None


class PerfGuidellmModule(_GuidellmBudgetMixin, TestModule):
    """GuideLLM real-world throughput & latency benchmark."""

    name = "perf_guidellm"
    display_name = "GuideLLM Real-World Benchmark"
    description = (
        "Simulates real-world traffic via GuideLLM's Poisson-arrival scheduler. "
        "Returns aggregate and per-request input/output TPS and TTFT/TPOT/ITL "
        "percentiles. "
        "Default score = 0.5×(input_tps/baseline) + 0.5×(output_tps/baseline); "
        "latency/uptime are redlines. Admin configures baselines and thresholds."
    )
    ParamsSchema = PerfGuidellmParams

    @classmethod
    def _budget_rates(cls, params) -> list:
        return [float(params.concurrency)]
    card_norm_baseline = CARD_NORM_BASELINE

    # Common HTTP response codes seen against LLM endpoints. Codes outside this
    # list still get counted and surfaced in metrics (key=http_status_<N>) — they
    # just won't have a pretty label/unit until added here.
    _HTTP_STATUS_DESCRIPTORS = [
        (200, "OK",                    True),
        (400, "Bad Request",           False),
        (401, "Unauthorized",          False),
        (403, "Forbidden",             False),
        (404, "Not Found",             False),
        (408, "Request Timeout",       False),
        (429, "Too Many Requests",     False),
        (500, "Internal Server Error", False),
        (502, "Bad Gateway",           False),
        (503, "Service Unavailable",   False),
        (504, "Gateway Timeout",       False),
    ]

    metrics_descriptors = [
        MetricDescriptor("input_tps",    "Input TPS",  "tok/s", "Aggregate input tokens per second",          higher_is_better=True),
        MetricDescriptor("output_tps",   "Output TPS", "tok/s", "Aggregate output tokens per second",         higher_is_better=True),
        MetricDescriptor("request_output_tps", "Per-Request Output TPS", "tok/s", "Output TPS per concurrent request (output_tps / concurrency) — the decode speed a single stream experiences", higher_is_better=True),
        MetricDescriptor("ttft_p99_ms",  "TTFT P99",   "ms",    "Time to first token, 99th percentile",       higher_is_better=False),
        MetricDescriptor("tpot_p99_ms",  "TPOT P99",   "ms",    "Time per output token, 99th percentile",     higher_is_better=False),
        MetricDescriptor("itl_p99_ms",   "ITL P99",    "ms",    "Inter-token latency, 99th percentile",       higher_is_better=False),
        MetricDescriptor("ttft_p90_ms",  "TTFT P90",   "ms",    "Time to first token, 90th percentile",       higher_is_better=False),
        MetricDescriptor("tpot_p90_ms",  "TPOT P90",   "ms",    "Time per output token, 90th percentile",     higher_is_better=False),
        MetricDescriptor("itl_p90_ms",   "ITL P90",    "ms",    "Inter-token latency, 90th percentile",       higher_is_better=False),
        MetricDescriptor("ttft_p50_ms",  "TTFT P50",   "ms",    "Time to first token, 50th percentile",       higher_is_better=False),
        MetricDescriptor("tpot_p50_ms",  "TPOT P50",   "ms",    "Time per output token, 50th percentile",     higher_is_better=False),
        MetricDescriptor("itl_p50_ms",   "ITL P50",    "ms",    "Inter-token latency, 50th percentile",       higher_is_better=False),
        MetricDescriptor("uptime",       "Uptime",     "%",     "Fraction of successful requests",             higher_is_better=True),
        MetricDescriptor("ttft_mean_ms", "TTFT Mean",  "ms",    "Time to first token, mean",                  higher_is_better=False),
        MetricDescriptor("tpot_mean_ms", "TPOT Mean",  "ms",    "Time per output token, mean",                higher_is_better=False),
        MetricDescriptor("itl_mean_ms",  "ITL Mean",   "ms",    "Inter-token latency, mean",                  higher_is_better=False),
        # Shared with perf_guidellm_sweep, which splats this list — declare them
        # here only, or the sweep ships each descriptor twice.
        MetricDescriptor("total_tps_mean",       "Total TPS",         "tok/s", "Aggregate total (input + output) tokens per second", higher_is_better=True),
        MetricDescriptor("reported_concurrency", "Reported Level",    "",      "Concurrency level the canonical metrics were taken from (the sweep's report_level param selects it; this module always reports the single level it ran)"),
        MetricDescriptor("duration_seconds",     "Measurement Window", "s",    "Length of the window the metrics describe — excludes the warmup and cooldown phases, so it is shorter than the run's wall-clock time"),
        MetricDescriptor("measured_requests",    "Measured Requests", "req",   "Requests counted in the reported metrics (warmup/cooldown excluded) — the sample size behind the percentiles. Far below what the run's duration or request-count cap should have produced means the sample was cut short, making the percentiles noisy and unstable between runs"),
        # Card-normalized TPM — display-only comparison metrics computed by the
        # platform worker (the card count lives on the submission's hardware
        # section, which modules never see): raw throughput x 60 x baseline / card count.
        MetricDescriptor("input_tpm_card_norm",  f"Input TPM ({CARD_NORM_BASELINE}-card norm.)",  "tok/min", f"Input tokens per minute normalized to {CARD_NORM_BASELINE} cards: input TPS x 60 x {CARD_NORM_BASELINE} / total card count (cards per machine x machine count; assumed {CARD_NORM_BASELINE} when hardware info is not provided)",  higher_is_better=True),
        MetricDescriptor("output_tpm_card_norm", f"Output TPM ({CARD_NORM_BASELINE}-card norm.)", "tok/min", f"Output tokens per minute normalized to {CARD_NORM_BASELINE} cards: output TPS x 60 x {CARD_NORM_BASELINE} / total card count (cards per machine x machine count; assumed {CARD_NORM_BASELINE} when hardware info is not provided)", higher_is_better=True),
        MetricDescriptor("total_tpm_card_norm",  f"Total TPM ({CARD_NORM_BASELINE}-card norm.)",  "tok/min", f"Total (input + output) tokens per minute normalized to {CARD_NORM_BASELINE} cards: total TPS x 60 x {CARD_NORM_BASELINE} / total card count (assumed {CARD_NORM_BASELINE} when hardware info is not provided)",                  higher_is_better=True),
        *[
            MetricDescriptor(
                f"http_status_{code}", f"HTTP {code}", "req",
                f"Count of HTTP {code} {reason} responses from the model endpoint",
                higher_is_better=hib,
            )
            for code, reason, hib in _HTTP_STATUS_DESCRIPTORS
        ],
    ]

    default_metric_configs = [
        MetricConfig("input_tps",   role="score",   weight=0.5, formula="ratio",   baseline=5000.0),
        MetricConfig("output_tps",  role="score",   weight=0.5, formula="ratio",   baseline=200.0),
        MetricConfig("ttft_p99_ms", role="redline", max_val=120000.0),
        MetricConfig("tpot_p99_ms", role="redline", max_val=200.0),
        MetricConfig("itl_p99_ms",  role="redline", max_val=150.0),
        MetricConfig("ttft_p50_ms", role="redline", max_val=60000.0),
        MetricConfig("tpot_p50_ms", role="redline", max_val=100.0),
        MetricConfig("itl_p50_ms",  role="redline", max_val=75.0),
        MetricConfig("uptime",      role="redline", min_val=0.90),
        MetricConfig("request_output_tps", role="display"),
        MetricConfig("total_tps_mean",       role="display"),
        MetricConfig("reported_concurrency", role="display"),
        MetricConfig("duration_seconds",     role="display"),
        MetricConfig("measured_requests",    role="display"),
        # P90 is informational rather than a redline: the P99/P50 caps above are
        # the agreed gate, and adding a third one would silently re-gate every
        # existing benchmark against a threshold nobody chose.
        MetricConfig("ttft_p90_ms", role="display"),
        MetricConfig("tpot_p90_ms", role="display"),
        MetricConfig("itl_p90_ms",  role="display"),
        MetricConfig("ttft_mean_ms", role="display"),
        MetricConfig("tpot_mean_ms", role="display"),
        MetricConfig("itl_mean_ms",  role="display"),
        *[MetricConfig(f"http_status_{code}", role="display")
          for code, _, _ in _HTTP_STATUS_DESCRIPTORS],
    ]

    def run(
        self,
        endpoint: EndpointConfig,
        params: BaseModel,
        output_dir: str,
        progress_cb: ProgressCallback = _noop_progress,
        cancel_event=None,
    ) -> ModuleResult:
        p: PerfGuidellmParams = params  # type: ignore[assignment]
        os.makedirs(output_dir, exist_ok=True)

        progress_cb(0.05, f"Starting guidellm: concurrency={p.concurrency}, "
                         f"input={p.input_tokens}, output={p.output_tokens}, "
                         f"duration={p.max_seconds}s")

        metrics = self._run_guidellm(endpoint, p, output_dir, progress_cb, cancel_event)

        if metrics is None:
            return ModuleResult(error="Backend failed to produce metrics")

        _promote_single_level_keys(metrics)
        # guidellm emits input_tps_mean / output_tps_mean; expose the canonical
        # bare names too, which is what benchmarks gate on.
        if "input_tps" not in metrics and "input_tps_mean" in metrics:
            metrics["input_tps"] = metrics["input_tps_mean"]
        if "output_tps" not in metrics and "output_tps_mean" in metrics:
            metrics["output_tps"] = metrics["output_tps_mean"]
        _add_flat_request_output_tps(metrics, p.concurrency)

        progress_cb(0.99, "Metrics collected — evaluator will compute score")
        logger.info("[perf_guidellm] metrics collected: input_tps=%.1f output_tps=%.1f",
                    metrics.get("input_tps", 0), metrics.get("output_tps", 0))
        return ModuleResult(metrics=metrics)

    def _run_guidellm(self, endpoint, p, output_dir, progress_cb, cancel_event):
        return run_guidellm_load(
            endpoint,
            rates=[float(p.concurrency)],
            input_tokens=p.input_tokens,
            output_tokens=p.output_tokens,
            max_seconds=p.max_seconds,
            request_timeout=p.request_timeout,
            warmup_seconds=p.warmup_seconds,
            dataset_path=p.dataset_path,
            processor_path=p.processor_path,
            output_dir=output_dir,
            progress_cb=progress_cb,
            cancel_event=cancel_event,
            log_tag="perf_guidellm",
        )


# Matches RealWorldTest's per-level suffix (`ttft_p99_ms_c8`). Kept local rather
# than imported from perf_guidellm_sweep, which imports *from* this module.
_LEVEL_SUFFIX_RE = re.compile(r"_c(\d+)$")


def _promote_single_level_keys(metrics: dict) -> None:
    """Expose this run's one concurrency level under flat, unsuffixed keys.

    RealWorldTest emits every stat suffixed with the level (`measured_requests_c8`)
    and promotes only a hardcoded subset to flat names, so stats it does not list
    — `duration_seconds`, `measured_requests`, the TPS percentiles — had no
    unsuffixed key here and could not be named in a MetricConfig. The sweep has
    them because its `_promote_canonical` copies a whole level wholesale; this is
    the same idea for the single level this module runs.

    The suffixed keys stay: they are this module's long-standing output contract.
    Promotion never overwrites — where RealWorldTest already chose a flat value it
    wins, though with one level the two are the same number by construction.
    """
    for key, val in list(metrics.items()):
        m = _LEVEL_SUFFIX_RE.search(key)
        if m:
            metrics.setdefault(key[: m.start()], val)


def _add_flat_request_output_tps(metrics: dict, concurrency: int) -> None:
    """Add the per-request (single-stream) output TPS: aggregate output_tps
    divided by the concurrency that produced it.

    Mirrors perf_guidellm_sweep's `request_output_tps`, so the two modules report
    the same number under the same key and a benchmark can gate on it either way.
    The sweep's version walks its nested per-level dicts, dividing each level's
    aggregate by that level; this module runs exactly one level, so it writes the
    flat top-level key directly — hence the different function name.

    Prefers guidellm's reported level over the requested concurrency so the
    numerator and denominator always describe the same run, falling back to the
    requested level when nothing was reported.
    """
    try:
        level = float(metrics.get("reported_concurrency") or concurrency)
        metrics["request_output_tps"] = float(metrics["output_tps"]) / level
    except (KeyError, TypeError, ValueError, ZeroDivisionError):
        return


# Runaway guard for the guidellm run. guidellm's own max_seconds bounds only its
# REQUEST phase — a run was observed completing that phase normally (full
# duration, every request 200) and then deadlocking in teardown, pinning the
# worker for 7+ hours with its forked processes parked forever. These size a
# hard external deadline: whichever of (expected x slack) or (expected + headroom)
# is larger, so short runs still get generous absolute room.
GUIDELLM_TIMEOUT_SLACK = float(os.getenv("GUIDELLM_TIMEOUT_SLACK", "3.0"))
GUIDELLM_TIMEOUT_HEADROOM_SECONDS = float(os.getenv("GUIDELLM_TIMEOUT_HEADROOM_SECONDS", "1800"))


def compute_guidellm_run_timeout(
    rates: list, warmup_seconds: float, max_seconds: float, request_timeout: float
) -> float:
    """Hard wall-clock budget for one guidellm invocation.

    Shared by the run path and the modules' ``time_budget_seconds`` so the
    worker's backstop is sized off the SAME number this run will actually
    enforce, instead of a second formula that could drift below it and abort
    healthy runs.

    Each concurrency level runs sequentially for (warmup + max_seconds), and when
    a level's duration expires guidellm still drains the requests already in
    flight — up to request_timeout per level, which the schema allows to be
    hours. Hence the explicit drain term.
    """
    total_seconds = len(rates) * (float(warmup_seconds) + float(max_seconds))
    return max(
        total_seconds * GUIDELLM_TIMEOUT_SLACK,
        total_seconds + GUIDELLM_TIMEOUT_HEADROOM_SECONDS,
    ) + len(rates) * float(request_timeout)


def run_guidellm_load(
    endpoint,
    *,
    rates: list,
    input_tokens: int,
    output_tokens: int,
    max_seconds: float,
    request_timeout: float,
    warmup_seconds: float,
    dataset_path: Optional[str],
    processor_path: Optional[str],
    output_dir: str,
    progress_cb: ProgressCallback,
    cancel_event,
    log_tag: str = "perf_guidellm",
    requests_per_concurrency: Optional[int] = None,
    random_seed: Optional[int] = None,
    warmup_fraction: Optional[float] = None,
    cooldown_fraction: Optional[float] = None,
):
    """Shared guidellm execution path for perf_guidellm and perf_guidellm_sweep.

    Runs guidellm's concurrent profile at each concurrency level in `rates`
    (sequentially, `max_seconds` each) and returns the merged metrics dict from
    RealWorldTest (per-level `*_c{N}` keys + canonical top-level keys), with
    HTTP status counts folded in. Returns None on failure.

    `requests_per_concurrency` switches levels to count-limited sampling: level
    c stops after c × that many requests, with `max_seconds` demoted to a
    safety cap (whichever fires first). None = duration-limited (legacy).

    `random_seed` seeds guidellm's synthetic prompt generator; None keeps the
    BenchConfig default. The same seed reproduces the same prompt sequence run
    after run, so callers that run repeatedly against one endpoint (the auto
    search) vary it to keep a server-side prefix cache from flattering them.

    `warmup_fraction` / `cooldown_fraction` are the shares of a count-limited
    level's requests discarded at its start and end (None = RealWorldTest's
    defaults, 10% / 5%). Duration-limited levels ignore them.
    """
    # REALWORLD_TEST_* env vars are read inside RealWorldTest.__init__ at
    # construction time (not module-import time), so setting them here
    # works correctly across submissions even in long-lived workers.
    # dataset_path and rates are passed explicitly because env values were
    # previously captured at module-import in b_realworld.py — see that
    # file's docstring.
    env_map = {
        "REALWORLD_TEST_PROMPT_TOKENS": str(input_tokens),
        "REALWORLD_TEST_OUTPUT_TOKENS": str(output_tokens),
        "REALWORLD_TEST_MAX_SECONDS":   str(int(max_seconds)),
        "REALWORLD_TEST_TIMEOUT":       str(int(request_timeout)),
        "REALWORLD_TEST_WARMUP":        str(warmup_seconds),
    }

    from utils.logger import HTTPX_STATUS_DUMP_DIR_ENV, read_httpx_status_dump
    status_dump_dir = os.path.join(output_dir, "_httpx_status")
    env_map[HTTPX_STATUS_DUMP_DIR_ENV] = status_dump_dir

    old_env = {k: os.environ.get(k) for k in env_map}
    for k, v in env_map.items():
        os.environ[k] = v

    # guidellm wall-time ≈ (warmup + max_seconds) per concurrency level. Use
    # this for the elapsed/total progress display since the upstream API
    # exposes no real progress hook.
    total_seconds = len(rates) * (float(warmup_seconds) + float(max_seconds))
    # Hard wall-clock budget. guidellm's own max_seconds only bounds its request
    # phase; a run has been seen finish that phase normally and then deadlock in
    # teardown, pinning the worker for hours with no way out. So bound the whole
    # thing externally, with generous slack for warmup, prefill on long prompts,
    # and aggregation — this is a runaway guard, not a schedule.
    run_timeout = compute_guidellm_run_timeout(
        rates, warmup_seconds, max_seconds, request_timeout
    )
    stop_progress = _start_elapsed_progress(progress_cb, total_seconds=total_seconds)
    try:
        from bench.tests.b_realworld import RealWorldTest
        test = RealWorldTest(
            endpoint.api_url, endpoint.model, endpoint.api_key, output_dir,
            dataset_path=dataset_path or None,
            processor_path=processor_path or None,
            rates=rates,
            requests_per_concurrency=requests_per_concurrency,
            random_seed=random_seed,
            warmup_fraction=warmup_fraction,
            cooldown_fraction=cooldown_fraction,
        )
        # Hard deadline for the underlying guidellm call (see run_timeout above).
        test.run_timeout = run_timeout
        logger.info(
            "[%s] guidellm budget: expected ~%.0fs (%d level(s) x (%.0fs warmup + %.0fs run)), "
            "hard timeout %.0fs (runaway guard: %sx slack, +%.0fs headroom, "
            "+%d x %.0fs in-flight drain)",
            log_tag, total_seconds, len(rates), warmup_seconds, max_seconds,
            run_timeout, GUIDELLM_TIMEOUT_SLACK, GUIDELLM_TIMEOUT_HEADROOM_SECONDS,
            len(rates), request_timeout,
        )
        result = test.run(cancel_event=cancel_event)
        progress_cb(0.9, "GuideLLM run complete, aggregating metrics")
        metrics = result.metrics if result.metrics else None
        if metrics is not None:
            # NOTE: status counts accumulate over the whole guidellm run — for a
            # multi-level sweep they are totals across all levels, not per-level.
            status_counts = read_httpx_status_dump(status_dump_dir)
            if status_counts:
                total = sum(status_counts.values())
                breakdown = " ".join(f"{c}={n}" for c, n in sorted(status_counts.items()))
                logger.info("[%s] HTTP status totals: total=%d %s", log_tag, total, breakdown)
                for code, n in status_counts.items():
                    metrics[f"http_status_{code}"] = float(n)
            elif sys.platform == "darwin":
                # guidellm >= 0.7.2 forces `spawn` for its workers on macOS, and a
                # spawned worker does not inherit the httpx counting filter
                # (utils.logger) unless its parent's __main__ happens to import it.
                # Linux — every deployment — uses `fork` and counts normally. The
                # metrics are omitted rather than reported as zero.
                logger.info("[%s] http_status_* unavailable on macOS (guidellm spawns "
                            "its workers there); counted on Linux", log_tag)
            else:
                logger.warning("[%s] no httpx status dumps found in %s", log_tag, status_dump_dir)
        return metrics
    except AllRequestsFailed:
        # Carries the concrete per-request reason; let the worker record it as
        # the run's error instead of collapsing it to "produced no metrics".
        raise
    except BenchmarkTimeout:
        # Same reasoning: "exceeded its Ns budget" is the whole diagnosis for a
        # wedged run, and is far more actionable than "produced no metrics".
        raise
    except Exception:
        from traceback import format_exc
        logger.error("[%s] guidellm run failed: %s", log_tag, format_exc())
        return None
    finally:
        stop_progress()
        for k, old_v in old_env.items():
            if old_v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = old_v


_PROGRESS_TICK_SECONDS = 30.0
# Map elapsed/total ∈ [0, 1] onto a [floor, ceiling] band so progress always lies
# between the module's initial "0.05 starting" tick and the post-run "0.9 done"
# tick. This keeps the bar monotonic and leaves room for the aggregation step.
_PROGRESS_FLOOR = 0.10
_PROGRESS_CEILING = 0.85


def _start_elapsed_progress(progress_cb, total_seconds: float):
    """Spawn a daemon thread that emits `elapsed/total` progress every few seconds.

    Returns a stop() callable. Always call stop() in a `finally` block. The
    progress_cb may raise (e.g. SubmissionCancelled) — that's caught and
    logged so the watcher thread always exits cleanly. The blocking benchmark
    call itself is what observes cancellation.
    """
    stop_event = threading.Event()

    def _loop() -> None:
        t0 = time.monotonic()
        while not stop_event.wait(timeout=_PROGRESS_TICK_SECONDS):
            elapsed = time.monotonic() - t0
            if total_seconds > 0:
                frac = min(elapsed / total_seconds, 1.0)
            else:
                frac = 0.0
            scaled = _PROGRESS_FLOOR + frac * (_PROGRESS_CEILING - _PROGRESS_FLOOR)
            msg = f"Running benchmark — {int(elapsed)}s / {int(total_seconds)}s elapsed"
            try:
                progress_cb(scaled, msg)
            except Exception:
                # The platform's progress_cb raises SubmissionCancelled on cancel;
                # let the main thread observe that via its own checks.
                return

    thread = threading.Thread(target=_loop, daemon=True, name="guidellm-progress")
    thread.start()

    def stop() -> None:
        stop_event.set()
        thread.join(timeout=2)

    return stop
