#!/usr/bin/env bash
# Generate the secrets a deployment needs, with strong random values.
#
# Writes a helm values file (default) or, with --env, the .env file
# `docker compose` reads, containing:
#   - the JWT signing key          (secrets.secretKey / SECRET_KEY)
#   - the Fernet key that encrypts stored endpoint API keys
#                                  (secrets.platformSecretKey / PLATFORM_SECRET_KEY)
#   - the first admin's email, username and password
#   - the Postgres password
#   - with --service-key: the key LLM AutoTune authenticates with
#     (secrets.serviceApiKey / SERVICE_API_KEY); give AutoTune the same value
#
# Usage:
#   scripts/gen-prod-secrets.sh [--out FILE] [--env] [--admin-email EMAIL] \
#                               [--admin-username NAME] [--service-key] [--force]
#
# Defaults:
#   --out             secrets.prod.yaml, or .env with --env
#   --admin-email     admin@example.com
#   --admin-username  admin
#
# Needs only openssl.
#
# Important:
#   - Refuses to overwrite an existing file unless --force is passed.
#   - Prints the admin password to stdout exactly once. Save it to a password
#     manager before closing your terminal — the script will not print it again.
#   - The generated file contains live credentials. Both default names are
#     git-ignored.
#
# Then:
#   helm upgrade --install llm-bench deploy/helm/llm-bench -f secrets.prod.yaml -n <ns>
#   docker compose --profile mock up -d          (with --env)

set -euo pipefail

OUT=""
FORMAT="helm"
ADMIN_EMAIL="admin@example.com"
ADMIN_USERNAME="admin"
FORCE="0"
SERVICE_KEY="0"

usage() {
  sed -n '2,33p' "$0"
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --out)            OUT="$2"; shift 2 ;;
    --env)            FORMAT="env"; shift ;;
    --admin-email)    ADMIN_EMAIL="$2"; shift 2 ;;
    --admin-username) ADMIN_USERNAME="$2"; shift 2 ;;
    --service-key)    SERVICE_KEY="1"; shift ;;
    --force)          FORCE="1"; shift ;;
    -h|--help)        usage ;;
    *) echo "Unknown arg: $1" >&2; usage ;;
  esac
done

if [[ -z "$OUT" ]]; then
  if [[ "$FORMAT" == "env" ]]; then OUT=".env"; else OUT="secrets.prod.yaml"; fi
fi

if [[ -e "$OUT" && "$FORCE" != "1" ]]; then
  echo "Refusing to overwrite existing file: $OUT" >&2
  echo "  Pass --force to allow, or --out PATH to choose a different file." >&2
  exit 1
fi

if ! command -v openssl >/dev/null; then
  echo "openssl is required." >&2
  exit 1
fi

# 32 random bytes, URL-safe base64. With its padding kept this is exactly the
# form a Fernet key takes; without it, a token that needs no quoting anywhere.
fernet_key() { openssl rand -base64 32 | tr '+/' '-_'; }
gen_token() { openssl rand -base64 32 | tr '+/' '-_' | tr -d '=\n'; }

PLATFORM_KEY="$(fernet_key)"
SECRET_KEY="$(gen_token)"
ADMIN_PASSWORD="$(gen_token)"
POSTGRES_PASSWORD="$(gen_token)"
SERVICE_API_KEY=""
[[ "$SERVICE_KEY" == "1" ]] && SERVICE_API_KEY="llmb_$(gen_token)"

umask 077
if [[ "$FORMAT" == "env" ]]; then
  cat > "$OUT" <<EOF
# docker compose secrets — DO NOT COMMIT.
# Generated by scripts/gen-prod-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
SECRET_KEY=${SECRET_KEY}
PLATFORM_SECRET_KEY=${PLATFORM_KEY}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# The key LLM AutoTune authenticates with (--service-key); empty = no service account.
SERVICE_API_KEY=${SERVICE_API_KEY}

# LLMBENCH_PORT=8080
# WORKER_PROCESSES=2
EOF
else
  cat > "$OUT" <<EOF
# Production secrets — DO NOT COMMIT.
# Generated by scripts/gen-prod-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# To rotate any field: regenerate this file and re-run the deploy. The platform
# re-reads secrets from the k8s Secret on pod restart.
#
# NOTE: rotating platformSecretKey invalidates every stored encrypted API key
# (submissions cannot decrypt their LLM credentials anymore). Only rotate if
# you intend to require users to re-enter API keys.

secrets:
  secretKey: "${SECRET_KEY}"
  platformSecretKey: "${PLATFORM_KEY}"
  adminEmail: "${ADMIN_EMAIL}"
  adminUsername: "${ADMIN_USERNAME}"
  adminPassword: "${ADMIN_PASSWORD}"
  serviceApiKey: "${SERVICE_API_KEY}"

postgres:
  password: "${POSTGRES_PASSWORD}"
EOF
fi
chmod 600 "$OUT"

echo "============================================================"
echo "Wrote ${OUT} (mode 0600)"
echo "============================================================"
echo "Admin login (save this — it will NOT be printed again):"
echo "  email:    ${ADMIN_EMAIL}"
echo "  username: ${ADMIN_USERNAME}"
echo "  password: ${ADMIN_PASSWORD}"
echo ""
echo "Next steps:"
echo "  1. Copy the admin password to a password manager NOW."
echo "  2. Confirm ${OUT} is gitignored (this repo ignores secrets*.yaml and .env)."
if [[ -n "$SERVICE_API_KEY" ]]; then
  echo "  2b. Give LLM AutoTune the same service key (llm-autotune chart: llmbench.apiKey):"
  echo "        ${SERVICE_API_KEY}"
fi
if [[ "$FORMAT" == "env" ]]; then
  echo "  3. Start it:  docker compose --profile mock up -d"
else
  echo "  3. Deploy:"
  echo "       helm upgrade --install llm-bench deploy/helm/llm-bench -f ${OUT} -n <ns>"
fi
echo "  4. After first login, rotate the admin password from the UI."
echo "============================================================"
