#!/usr/bin/env bash
# Generate a production secrets.yaml with strong random values.
#
# Writes a fresh helm values file containing:
#   - secrets.secretKey         (JWT signing key, 32-byte url-safe)
#   - secrets.platformSecretKey (Fernet key for API-key encryption, 32-byte b64)
#   - secrets.adminEmail        (default admin@example.com, override with flag)
#   - secrets.adminUsername     (default "admin", override with flag)
#   - secrets.adminPassword     (32-byte url-safe)
#   - postgres.password         (32-byte url-safe)
#   - secrets.serviceApiKey     (only with --service-key: the key LLM AutoTune
#                                authenticates with; give it the same value)
#
# Usage:
#   scripts/gen-prod-secrets.sh [--out FILE] [--admin-email EMAIL] \
#                               [--admin-username NAME] [--service-key] [--force]
#
# Defaults:
#   --out             secrets.prod.yaml
#   --admin-email     admin@example.com
#   --admin-username  admin
#
# Important:
#   - Refuses to overwrite an existing file unless --force is passed.
#   - Prints the admin password to stdout exactly once. Save it to a password
#     manager before closing your terminal — the script will not print it again.
#   - The generated file contains live credentials. Add it to .gitignore.
#
# After running, deploy with:
#   helm upgrade --install llm-bench deploy/helm/llm-bench -f secrets.prod.yaml -n <ns>

set -euo pipefail

OUT="secrets.prod.yaml"
ADMIN_EMAIL="admin@example.com"
ADMIN_USERNAME="admin"
FORCE="0"
SERVICE_KEY="0"

usage() {
  sed -n '2,28p' "$0"
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --out)            OUT="$2"; shift 2 ;;
    --admin-email)    ADMIN_EMAIL="$2"; shift 2 ;;
    --admin-username) ADMIN_USERNAME="$2"; shift 2 ;;
    --service-key)    SERVICE_KEY="1"; shift ;;
    --force)          FORCE="1"; shift ;;
    -h|--help)        usage ;;
    *) echo "Unknown arg: $1" >&2; usage ;;
  esac
done

if [[ -e "$OUT" && "$FORCE" != "1" ]]; then
  echo "Refusing to overwrite existing file: $OUT" >&2
  echo "  Pass --force to allow, or --out PATH to choose a different file." >&2
  exit 1
fi

if ! command -v python3 >/dev/null; then
  echo "python3 required (used to generate Fernet key)." >&2
  exit 1
fi

# Fernet key — must be 32-byte url-safe base64. cryptography enforces this.
if ! PLATFORM_KEY="$(python3 -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())' 2>/dev/null)"; then
  echo "Failed to generate Fernet key. Install 'cryptography':" >&2
  echo "  pip install cryptography     (or: uv pip install cryptography)" >&2
  exit 1
fi

# 32-byte url-safe random tokens for the rest.
gen_token() { python3 -c 'import secrets; print(secrets.token_urlsafe(32))'; }

SECRET_KEY="$(gen_token)"
ADMIN_PASSWORD="$(gen_token)"
POSTGRES_PASSWORD="$(gen_token)"
SERVICE_API_KEY=""
[[ "$SERVICE_KEY" == "1" ]] && SERVICE_API_KEY="llmb_$(gen_token)"

umask 077
cat > "$OUT" <<EOF
# Production secrets — DO NOT COMMIT.
# Generated by scripts/gen-prod-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# To rotate any field: regenerate this file and re-run the deploy. The platform
# re-reads secrets from the k8s Secret on pod restart.
#
# NOTE: rotating platformSecretKey invalidates every stored encrypted API key
# (submissions cannot decrypt their LLM credentials anymore). Only rotate if
# you intend to require users to re-enter API keys.

secrets:
  secretKey: "${SECRET_KEY}"
  platformSecretKey: "${PLATFORM_KEY}"
  adminEmail: "${ADMIN_EMAIL}"
  adminUsername: "${ADMIN_USERNAME}"
  adminPassword: "${ADMIN_PASSWORD}"
  serviceApiKey: "${SERVICE_API_KEY}"

postgres:
  password: "${POSTGRES_PASSWORD}"
EOF
chmod 600 "$OUT"

echo "============================================================"
echo "Wrote ${OUT} (mode 0600)"
echo "============================================================"
echo "Admin login (save this — it will NOT be printed again):"
echo "  email:    ${ADMIN_EMAIL}"
echo "  username: ${ADMIN_USERNAME}"
echo "  password: ${ADMIN_PASSWORD}"
echo ""
echo "Next steps:"
echo "  1. Copy the admin password to a password manager NOW."
echo "  2. Confirm ${OUT} is gitignored (this repo ignores secrets*.yaml)."
if [[ -n "$SERVICE_API_KEY" ]]; then
  echo "  2b. Give LLM AutoTune the same service key (llm-autotune chart: llmbench.apiKey):"
  echo "        ${SERVICE_API_KEY}"
fi
echo "  3. Deploy:"
echo "       helm upgrade --install llm-bench deploy/helm/llm-bench -f ${OUT} -n <ns>"
echo "  4. After first login, rotate the admin password from the UI."
echo "============================================================"
